# Generated by Django 4.1.4 on 2022-12-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("UserProfil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker_symbole", models.CharField(max_length=10)),
                ("qty", models.CharField(max_length=10)),
                ("price", models.CharField(max_length=10)),
                (
                    "possition",
                    models.CharField(
                        choices=[
                            ("LONG", "Long"),
                            ("SHORT", "Short"),
                            ("CALL", "Call"),
                            ("PUT", "Put"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type_trade",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("OPTION", "Option"),
                            ("FUTURES", "Futures"),
                        ],
                        max_length=10,
                    ),
                ),
                ("Open_date", models.DateField(max_length=20)),
                ("close_date", models.DateField(max_length=20)),
                ("journal", models.TextField(max_length=20)),
                ("creation_date", models.DateField(auto_now_add=True)),
                (
                    "journal_user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserProfil.user",
                    ),
                ),
            ],
        ),
    ]
