# Generated by Django 4.1.4 on 2022-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_first_name", models.CharField(max_length=20)),
                ("user_last_name", models.CharField(max_length=20)),
                ("user_email", models.EmailField(max_length=100)),
                ("user_user_name", models.CharField(max_length=20)),
                ("user_join_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
